# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/CWBierzapfanlage.ui'
#
# Created: Thu Jun  8 17:24:50 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CWBierzapfanlageGUI(object):
    def setupUi(self, CWBierzapfanlageGUI):
        CWBierzapfanlageGUI.setObjectName(_fromUtf8("CWBierzapfanlageGUI"))
        CWBierzapfanlageGUI.resize(730, 729)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CWBierzapfanlageGUI.sizePolicy().hasHeightForWidth())
        CWBierzapfanlageGUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(CWBierzapfanlageGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnExit = QtGui.QPushButton(self.centralwidget)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.gridLayout_4.addWidget(self.btnExit, 5, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSetting = QtGui.QWidget()
        self.tabSetting.setObjectName(_fromUtf8("tabSetting"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabSetting)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblDefineDetectionArea = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDefineDetectionArea.sizePolicy().hasHeightForWidth())
        self.lblDefineDetectionArea.setSizePolicy(sizePolicy)
        self.lblDefineDetectionArea.setAutoFillBackground(False)
        self.lblDefineDetectionArea.setScaledContents(False)
        self.lblDefineDetectionArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDefineDetectionArea.setObjectName(_fromUtf8("lblDefineDetectionArea"))
        self.verticalLayout.addWidget(self.lblDefineDetectionArea)
        self.hlLeftLeftBorder = QtGui.QHBoxLayout()
        self.hlLeftLeftBorder.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hlLeftLeftBorder.setObjectName(_fromUtf8("hlLeftLeftBorder"))
        self.lblLeftLeftBorder = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftLeftBorder.sizePolicy().hasHeightForWidth())
        self.lblLeftLeftBorder.setSizePolicy(sizePolicy)
        self.lblLeftLeftBorder.setObjectName(_fromUtf8("lblLeftLeftBorder"))
        self.hlLeftLeftBorder.addWidget(self.lblLeftLeftBorder)
        self.hsLeftLeftBorder = QtGui.QSlider(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hsLeftLeftBorder.sizePolicy().hasHeightForWidth())
        self.hsLeftLeftBorder.setSizePolicy(sizePolicy)
        self.hsLeftLeftBorder.setMaximum(255)
        self.hsLeftLeftBorder.setOrientation(QtCore.Qt.Horizontal)
        self.hsLeftLeftBorder.setObjectName(_fromUtf8("hsLeftLeftBorder"))
        self.hlLeftLeftBorder.addWidget(self.hsLeftLeftBorder)
        self.verticalLayout.addLayout(self.hlLeftLeftBorder)
        self.hlLeftRightBorder = QtGui.QHBoxLayout()
        self.hlLeftRightBorder.setObjectName(_fromUtf8("hlLeftRightBorder"))
        self.lblLeftRightBorder = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLeftRightBorder.sizePolicy().hasHeightForWidth())
        self.lblLeftRightBorder.setSizePolicy(sizePolicy)
        self.lblLeftRightBorder.setObjectName(_fromUtf8("lblLeftRightBorder"))
        self.hlLeftRightBorder.addWidget(self.lblLeftRightBorder)
        self.hsLeftRightBorder = QtGui.QSlider(self.tabSetting)
        self.hsLeftRightBorder.setMaximum(255)
        self.hsLeftRightBorder.setOrientation(QtCore.Qt.Horizontal)
        self.hsLeftRightBorder.setObjectName(_fromUtf8("hsLeftRightBorder"))
        self.hlLeftRightBorder.addWidget(self.hsLeftRightBorder)
        self.verticalLayout.addLayout(self.hlLeftRightBorder)
        self.lblDefineRightDetectionArea = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDefineRightDetectionArea.sizePolicy().hasHeightForWidth())
        self.lblDefineRightDetectionArea.setSizePolicy(sizePolicy)
        self.lblDefineRightDetectionArea.setObjectName(_fromUtf8("lblDefineRightDetectionArea"))
        self.verticalLayout.addWidget(self.lblDefineRightDetectionArea)
        self.hlRightLeftBorder = QtGui.QHBoxLayout()
        self.hlRightLeftBorder.setObjectName(_fromUtf8("hlRightLeftBorder"))
        self.lblRightLeftBorder = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRightLeftBorder.sizePolicy().hasHeightForWidth())
        self.lblRightLeftBorder.setSizePolicy(sizePolicy)
        self.lblRightLeftBorder.setObjectName(_fromUtf8("lblRightLeftBorder"))
        self.hlRightLeftBorder.addWidget(self.lblRightLeftBorder)
        self.hsRightLeftBorder = QtGui.QSlider(self.tabSetting)
        self.hsRightLeftBorder.setMaximum(255)
        self.hsRightLeftBorder.setOrientation(QtCore.Qt.Horizontal)
        self.hsRightLeftBorder.setObjectName(_fromUtf8("hsRightLeftBorder"))
        self.hlRightLeftBorder.addWidget(self.hsRightLeftBorder)
        self.verticalLayout.addLayout(self.hlRightLeftBorder)
        self.hlRightRightBorder = QtGui.QHBoxLayout()
        self.hlRightRightBorder.setObjectName(_fromUtf8("hlRightRightBorder"))
        self.lblRightRightBorder = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRightRightBorder.sizePolicy().hasHeightForWidth())
        self.lblRightRightBorder.setSizePolicy(sizePolicy)
        self.lblRightRightBorder.setObjectName(_fromUtf8("lblRightRightBorder"))
        self.hlRightRightBorder.addWidget(self.lblRightRightBorder)
        self.hsRightRightBorder = QtGui.QSlider(self.tabSetting)
        self.hsRightRightBorder.setOrientation(QtCore.Qt.Horizontal)
        self.hsRightRightBorder.setObjectName(_fromUtf8("hsRightRightBorder"))
        self.hlRightRightBorder.addWidget(self.hsRightRightBorder)
        self.verticalLayout.addLayout(self.hlRightRightBorder)
        self.lblDistanceBetween = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDistanceBetween.sizePolicy().hasHeightForWidth())
        self.lblDistanceBetween.setSizePolicy(sizePolicy)
        self.lblDistanceBetween.setObjectName(_fromUtf8("lblDistanceBetween"))
        self.verticalLayout.addWidget(self.lblDistanceBetween)
        self.hlDistance = QtGui.QHBoxLayout()
        self.hlDistance.setObjectName(_fromUtf8("hlDistance"))
        self.lblDistance = QtGui.QLabel(self.tabSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDistance.sizePolicy().hasHeightForWidth())
        self.lblDistance.setSizePolicy(sizePolicy)
        self.lblDistance.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblDistance.setObjectName(_fromUtf8("lblDistance"))
        self.hlDistance.addWidget(self.lblDistance)
        self.hsDistance = QtGui.QSlider(self.tabSetting)
        self.hsDistance.setOrientation(QtCore.Qt.Horizontal)
        self.hsDistance.setObjectName(_fromUtf8("hsDistance"))
        self.hlDistance.addWidget(self.hsDistance)
        self.verticalLayout.addLayout(self.hlDistance)
        self.tabWidget.addTab(self.tabSetting, _fromUtf8(""))
        self.tabConfiguration = QtGui.QWidget()
        self.tabConfiguration.setObjectName(_fromUtf8("tabConfiguration"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabConfiguration)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblPlaceholderImage = QtGui.QLabel(self.tabConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPlaceholderImage.sizePolicy().hasHeightForWidth())
        self.lblPlaceholderImage.setSizePolicy(sizePolicy)
        self.lblPlaceholderImage.setText(_fromUtf8(""))
        self.lblPlaceholderImage.setObjectName(_fromUtf8("lblPlaceholderImage"))
        self.gridLayout_7.addWidget(self.lblPlaceholderImage, 0, 0, 1, 1)
        self.glConfiguration = QtGui.QGridLayout()
        self.glConfiguration.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.glConfiguration.setContentsMargins(-1, -1, 0, -1)
        self.glConfiguration.setHorizontalSpacing(1)
        self.glConfiguration.setVerticalSpacing(3)
        self.glConfiguration.setObjectName(_fromUtf8("glConfiguration"))
        self.cbConfiguration = QtGui.QComboBox(self.tabConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.cbConfiguration.sizePolicy().hasHeightForWidth())
        self.cbConfiguration.setSizePolicy(sizePolicy)
        self.cbConfiguration.setObjectName(_fromUtf8("cbConfiguration"))
        self.glConfiguration.addWidget(self.cbConfiguration, 0, 1, 1, 1)
        self.lblPlaceholder = QtGui.QLabel(self.tabConfiguration)
        self.lblPlaceholder.setText(_fromUtf8(""))
        self.lblPlaceholder.setObjectName(_fromUtf8("lblPlaceholder"))
        self.glConfiguration.addWidget(self.lblPlaceholder, 2, 1, 1, 1)
        self.edtConfigurationName = QtGui.QLineEdit(self.tabConfiguration)
        self.edtConfigurationName.setObjectName(_fromUtf8("edtConfigurationName"))
        self.glConfiguration.addWidget(self.edtConfigurationName, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.glConfiguration, 1, 0, 1, 1)
        self.hlConfiguration = QtGui.QHBoxLayout()
        self.hlConfiguration.setObjectName(_fromUtf8("hlConfiguration"))
        self.btnSaveConfiguration = QtGui.QPushButton(self.tabConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveConfiguration.sizePolicy().hasHeightForWidth())
        self.btnSaveConfiguration.setSizePolicy(sizePolicy)
        self.btnSaveConfiguration.setObjectName(_fromUtf8("btnSaveConfiguration"))
        self.hlConfiguration.addWidget(self.btnSaveConfiguration)
        self.btnDeleteConfiguration = QtGui.QPushButton(self.tabConfiguration)
        self.btnDeleteConfiguration.setObjectName(_fromUtf8("btnDeleteConfiguration"))
        self.hlConfiguration.addWidget(self.btnDeleteConfiguration)
        self.gridLayout_7.addLayout(self.hlConfiguration, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabConfiguration, _fromUtf8(""))
        self.tabLog = QtGui.QWidget()
        self.tabLog.setObjectName(_fromUtf8("tabLog"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabLog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.edtLog = QtGui.QTextEdit(self.tabLog)
        self.edtLog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtLog.setBaseSize(QtCore.QSize(0, 0))
        self.edtLog.setFrameShape(QtGui.QFrame.Box)
        self.edtLog.setFrameShadow(QtGui.QFrame.Plain)
        self.edtLog.setReadOnly(True)
        self.edtLog.setObjectName(_fromUtf8("edtLog"))
        self.gridLayout_5.addWidget(self.edtLog, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLog, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.cbDemoModus = QtGui.QCheckBox(self.centralwidget)
        self.cbDemoModus.setObjectName(_fromUtf8("cbDemoModus"))
        self.gridLayout_4.addWidget(self.cbDemoModus, 4, 0, 1, 1)
        CWBierzapfanlageGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(CWBierzapfanlageGUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CWBierzapfanlageGUI.setStatusBar(self.statusbar)

        self.retranslateUi(CWBierzapfanlageGUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CWBierzapfanlageGUI)

    def retranslateUi(self, CWBierzapfanlageGUI):
        CWBierzapfanlageGUI.setWindowTitle(_translate("CWBierzapfanlageGUI", "CWBierzapfanlage", None))
        self.btnExit.setText(_translate("CWBierzapfanlageGUI", "Exit", None))
        self.lblDefineDetectionArea.setText(_translate("CWBierzapfanlageGUI", "Define left detection area:", None))
        self.lblLeftLeftBorder.setText(_translate("CWBierzapfanlageGUI", "Left border", None))
        self.lblLeftRightBorder.setText(_translate("CWBierzapfanlageGUI", "Right border", None))
        self.lblDefineRightDetectionArea.setText(_translate("CWBierzapfanlageGUI", "Define right detection area:", None))
        self.lblRightLeftBorder.setText(_translate("CWBierzapfanlageGUI", "Left border", None))
        self.lblRightRightBorder.setText(_translate("CWBierzapfanlageGUI", "Right border", None))
        self.lblDistanceBetween.setText(_translate("CWBierzapfanlageGUI", "Distance betwen foam (blue) and top horizontal glass edge (green): ", None))
        self.lblDistance.setText(_translate("CWBierzapfanlageGUI", "Distance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetting), _translate("CWBierzapfanlageGUI", "Setting", None))
        self.btnSaveConfiguration.setText(_translate("CWBierzapfanlageGUI", "Save", None))
        self.btnDeleteConfiguration.setText(_translate("CWBierzapfanlageGUI", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfiguration), _translate("CWBierzapfanlageGUI", "Configuration", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("CWBierzapfanlageGUI", "Log", None))
        self.cbDemoModus.setText(_translate("CWBierzapfanlageGUI", "Demo Modus", None))

